/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho02.iu;


import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.MaskFormatter;
import trabalho02.controlador.Controlador;
import trabalho02.modelo.Aluno;
import trabalho02.modelo.Professor;
import trabalho02.modelo.Usuario;
/**
 *
 * @author MrFELIS
 */
public class IUAddUsuario extends javax.swing.JDialog {

    /**
     * Creates new form IUAddUsuario
     */
    public IUAddUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        completar();
        completarProfessor();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        codText = new javax.swing.JTextField();
        nomeText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cursoBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        anoText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cadastrarBotao = new javax.swing.JButton();
        cancelarBotao = new javax.swing.JButton();
        alerta = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        removerBotao = new javax.swing.JButton();
        pesquisa = new javax.swing.JTextField();
        atualizarBotao = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        codText2 = new javax.swing.JTextField();
        nomeText2 = new javax.swing.JTextField();
        jLabel1P = new javax.swing.JLabel();
        jLabel2P = new javax.swing.JLabel();
        cursoBox2 = new javax.swing.JComboBox<>();
        jLabel3P = new javax.swing.JLabel();
        cadastrarBotao2 = new javax.swing.JButton();
        cancelarBotao2 = new javax.swing.JButton();
        alerta2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane2P = new javax.swing.JScrollPane();
        tabela2 = new javax.swing.JTable();
        removerBotao2 = new javax.swing.JButton();
        pesquisa2 = new javax.swing.JTextField();
        atualizarBotao2 = new javax.swing.JButton();
        sairBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setToolTipText("");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Usuário"));
        jPanel3.setPreferredSize(new java.awt.Dimension(680, 180));

        codText.setToolTipText("Maxímo 6 Digitos");
        codText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codTextFocusLost(evt);
            }
        });
        codText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codTextActionPerformed(evt);
            }
        });
        codText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codTextKeyTyped(evt);
            }
        });

        nomeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeTextKeyTyped(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Nome do Aluno");

        cursoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".", "Arquitetura e Urbanismo", "Ciência da Computação", "Educação Fisica", "Engenharia Cartografica", "Estatística", "Física", "Fisioterapia", "Matemática", "Química" }));
        cursoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoBoxActionPerformed(evt);
            }
        });
        cursoBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cursoBoxKeyPressed(evt);
            }
        });

        jLabel3.setText("Curso");

        anoText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                anoTextFocusLost(evt);
            }
        });
        anoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                anoTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anoTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anoTextKeyTyped(evt);
            }
        });

        jLabel4.setText("Ano");

        cadastrarBotao.setText("Cadastrar");
        cadastrarBotao.setPreferredSize(new java.awt.Dimension(80, 20));
        cadastrarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBotaoActionPerformed(evt);
            }
        });

        cancelarBotao.setText("Limpar");
        cancelarBotao.setPreferredSize(new java.awt.Dimension(80, 20));
        cancelarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotaoActionPerformed(evt);
            }
        });

        alerta.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(anoText)
                            .addComponent(codText))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cursoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cadastrarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(alerta))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Curso", "Ano"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.getTableHeader().setResizingAllowed(false);
        tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabela);

        removerBotao.setText("Remover");
        removerBotao.setToolTipText("Remover Selecionado [Todos Apenas em Configurações ]");
        removerBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBotaoActionPerformed(evt);
            }
        });

        pesquisa.setText("Pesquisar por Nome dos Alunos Cadastrados");
        pesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pesquisaFocusLost(evt);
            }
        });
        pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaActionPerformed(evt);
            }
        });
        pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisaKeyReleased(evt);
            }
        });

        atualizarBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizar.png"))); // NOI18N
        atualizarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(removerBotao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(removerBotao)
                        .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(atualizarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Aluno", jPanel1);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Professor"));
        jPanel11.setPreferredSize(new java.awt.Dimension(680, 180));

        codText2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codText2FocusLost(evt);
            }
        });
        codText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codText2ActionPerformed(evt);
            }
        });
        codText2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codText2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codText2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codText2KeyTyped(evt);
            }
        });

        nomeText2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeText2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeText2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeText2KeyTyped(evt);
            }
        });

        jLabel1P.setText("Código");

        jLabel2P.setText("Nome do Professor");

        cursoBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".", "Especialização", "MBA (Master in Business Administration)", "Mestrado Profissional", "Mestrado Acadêmico", "Douturado", "Livre-Docência" }));
        cursoBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoBox2ActionPerformed(evt);
            }
        });
        cursoBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cursoBox2KeyPressed(evt);
            }
        });

        jLabel3P.setText("Titulação");

        cadastrarBotao2.setText("Cadastrar");
        cadastrarBotao2.setPreferredSize(new java.awt.Dimension(80, 20));
        cadastrarBotao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBotao2ActionPerformed(evt);
            }
        });

        cancelarBotao2.setText("Limpar");
        cancelarBotao2.setPreferredSize(new java.awt.Dimension(80, 20));
        cancelarBotao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotao2ActionPerformed(evt);
            }
        });

        alerta2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1P, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(codText2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2P, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeText2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(alerta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(cursoBox2, 0, 479, Short.MAX_VALUE)
                                .addGap(16, 16, 16)
                                .addComponent(cadastrarBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(cancelarBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel3P, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1P)
                    .addComponent(jLabel2P))
                .addGap(9, 9, 9)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeText2)
                    .addComponent(codText2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3P)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursoBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(alerta2))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Titulação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabela2.getTableHeader().setResizingAllowed(false);
        tabela2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2P.setViewportView(tabela2);

        removerBotao2.setText("Remover");
        removerBotao2.setToolTipText("Remover Selecionado [Todos Apenas em Configurações ]");
        removerBotao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBotao2ActionPerformed(evt);
            }
        });

        pesquisa2.setText("Pesquisar por Nome dos Professores Cadastrados");
        pesquisa2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pesquisa2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pesquisa2FocusLost(evt);
            }
        });
        pesquisa2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisa2KeyReleased(evt);
            }
        });

        atualizarBotao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizar.png"))); // NOI18N
        atualizarBotao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBotao2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2P, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(removerBotao2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisa2, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizarBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2P, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atualizarBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(removerBotao2)
                        .addComponent(pesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Professor", jPanel6);

        sairBotao.setText("Voltar");
        sairBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sairBotao)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(sairBotao)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void completarProfessor(){
       cancelarBotao2.setToolTipText("Limpa Todos Os Campos Preenchidos");
       atualizarBotao2.setToolTipText("Atualizar Tabela");
       Controlador control = new Controlador();
       ArrayList<Usuario> usuario = control.getUserBusca("Professor");
       DefaultTableModel model2 = (DefaultTableModel) tabela2.getModel();
       
       Professor prof = null;
       if(usuario !=null){
       for(Usuario user: usuario){
        prof=(Professor) user;
        Object linha[] = new Object[4];
        linha[0] = user.getCodUsuario();
        linha[1] = user.getNome();
        linha[2] = prof.getTitulacao();
        model2.addRow(linha);
        }
       }
    }
    private void removerTabelaProfessor(){
       DefaultTableModel model2 = (DefaultTableModel) tabela2.getModel();
       int tam = tabela2.getRowCount();
       for(int i=0; i<tam; i++){
           model2.removeRow(0);
       }
    } 
    private void atualizarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBotaoActionPerformed
        // TODO add your handling code here:
        removerTabela();
        completar();
    }//GEN-LAST:event_atualizarBotaoActionPerformed

    private void pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaKeyReleased
        // TODO add your handling code here:
        pesquisa.setText(pesquisa.getText().replaceAll("[^A-Z | ^a-z]",""));
        TableRowSorter<TableModel> sorter = null;
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        sorter = new TableRowSorter<>(model);
        tabela.setRowSorter(sorter);
        String texto = pesquisa.getText();
        if(texto.length() != 0){
            sorter.setRowFilter(RowFilter.regexFilter(texto));
        }
    }//GEN-LAST:event_pesquisaKeyReleased

    private void pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaActionPerformed

    private void pesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesquisaFocusLost
        // TODO add your handling code here:
        pesquisa.setText("Pesquisar por Nome dos Alunos Cadastrados");
    }//GEN-LAST:event_pesquisaFocusLost

    private void pesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesquisaFocusGained
        // TODO add your handling code here:
        pesquisa.setText("");
    }//GEN-LAST:event_pesquisaFocusGained

    private void removerBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBotaoActionPerformed
        // TODO add your handling code here:
        Controlador control = new Controlador();
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();

        TableRowSorter<TableModel> sorter = null;
        int linha=-1;
        linha = tabela.getSelectedRow();

        if(linha>=0){
            String cod;
            cod = (String) (tabela.getValueAt(linha, 0));
            control.removerUsuario(cod);
            linha=tabela.convertRowIndexToModel(linha);
            model.removeRow(linha);
            pesquisa.setText("Pesquisar por Nome dos Alunos Cadastrados");

            tabela.setRowSorter(null);
        }
    }//GEN-LAST:event_removerBotaoActionPerformed

    private void nomeText2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeText2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cursoBox2.requestFocus();
        }
    }//GEN-LAST:event_nomeText2KeyPressed

    private void nomeText2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeText2KeyReleased
        // TODO add your handling code here:
        nomeText2.setText(nomeText2.getText().replaceAll("[^A-Z | ^a-z]",""));
    }//GEN-LAST:event_nomeText2KeyReleased

    private void cursoBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursoBox2ActionPerformed

    private void cursoBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cursoBox2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            getRootPane().setDefaultButton(cadastrarBotao2);
        }
    }//GEN-LAST:event_cursoBox2KeyPressed

    private void cadastrarBotao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBotao2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model2 = (DefaultTableModel) tabela2.getModel();

        String cod = codText2.getText();
        String nome = nomeText2.getText();
        String curso = (String) cursoBox2.getSelectedItem();
        if(cod.isEmpty() || nome.isEmpty() ||  curso == "."){
            alerta2.setText("Preencha todos os campos");
            alerta2.setVisible(true);
        }
        else{
            Controlador control = new Controlador();
            control.addProfessor(cod, nome, curso);

            Object linha[] = new Object[4];
            linha[0] = cod;
            linha[1] = nome;
            linha[2] = curso;

            model2.addRow(linha);
            alerta2.setText("Professor Cadastrado");
            alerta2.setVisible(true);
            codText2.setText("");
            codText2.requestFocus();
            nomeText2.setText("");
            cursoBox2.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cadastrarBotao2ActionPerformed

    private void cancelarBotao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotao2ActionPerformed
        // TODO add your handling code here:
        alerta2.setVisible(false);
        codText2.setText("");
        codText2.requestFocus();
        nomeText2.setText("");
        cursoBox2.setSelectedIndex(0);
    }//GEN-LAST:event_cancelarBotao2ActionPerformed

    private void sairBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBotaoActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_sairBotaoActionPerformed

    private void removerBotao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBotao2ActionPerformed
        // TODO add your handling code here:
        Controlador control = new Controlador();
        DefaultTableModel model2 = (DefaultTableModel) tabela2.getModel();

        TableRowSorter<TableModel> sorter = null;
        int linha=-1;
        linha = tabela2.getSelectedRow();

        if(linha>=0){
            String cod;
            cod = (String) (tabela2.getValueAt(linha, 0));
            control.removerUsuario(cod);
            linha=tabela2.convertRowIndexToModel(linha);
            model2.removeRow(linha);
            pesquisa2.setText("Pesquisar por Nome dos Professores Cadastrados");

            tabela2.setRowSorter(null);
        }
    }//GEN-LAST:event_removerBotao2ActionPerformed

    private void pesquisa2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisa2KeyReleased
        // TODO add your handling code here:
        pesquisa2.setText(pesquisa2.getText().replaceAll("[^A-Z | ^a-z]",""));
        TableRowSorter<TableModel> sorter = null;
        DefaultTableModel model = (DefaultTableModel) tabela2.getModel();
        sorter = new TableRowSorter<>(model);
        tabela2.setRowSorter(sorter);
        String texto = pesquisa2.getText();
        if(texto.length() != 0){
            sorter.setRowFilter(RowFilter.regexFilter(texto));
        }
    }//GEN-LAST:event_pesquisa2KeyReleased

    private void pesquisa2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesquisa2FocusLost
        // TODO add your handling code here:
        pesquisa2.setText("Pesquisar por Nome dos Professores Cadastrados");
    }//GEN-LAST:event_pesquisa2FocusLost

    private void pesquisa2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesquisa2FocusGained
        // TODO add your handling code here:
        pesquisa2.setText("");
    }//GEN-LAST:event_pesquisa2FocusGained

    private void atualizarBotao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBotao2ActionPerformed
        // TODO add your handling code here:
        removerTabelaProfessor();
        completarProfessor();
    }//GEN-LAST:event_atualizarBotao2ActionPerformed

    private void codText2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codText2KeyReleased
        // TODO add your handling code here:
        codText2.setText(codText2.getText().replaceAll("[^0-9]",""));
        
        
    }//GEN-LAST:event_codText2KeyReleased

    private void codText2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codText2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            nomeText2.requestFocus();
        }
    }//GEN-LAST:event_codText2KeyPressed

    private void codText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codText2ActionPerformed

    private void codText2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codText2KeyTyped
        // TODO add your handling code here:
        if(codText2.getText().length() == 6){
            evt.consume();
        }
    }//GEN-LAST:event_codText2KeyTyped

    private void cancelarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotaoActionPerformed
        // TODO add your handling code here:
        alerta.setVisible(false);
        codText.setText("");
        codText.requestFocus();
        nomeText.setText("");
        anoText.setText("");
        cursoBox.setSelectedIndex(0);
    }//GEN-LAST:event_cancelarBotaoActionPerformed

    private void cadastrarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBotaoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();

        String cod = codText.getText();
        String nome = nomeText.getText();
        String sano= anoText.getText();
        String curso = (String) cursoBox.getSelectedItem();
        if(cod.isEmpty() || nome.isEmpty() || sano.isEmpty() || curso == "."){
            alerta.setText("Preencha todos os campos");
            alerta.setVisible(true);
        }
        else{
            Integer ano = Integer.parseInt(anoText.getText());

            Controlador control = new Controlador();
            control.addAluno(cod, nome, curso, ano);

            Object linha[] = new Object[4];
            linha[0] = cod;
            linha[1] = nome;
            linha[2] = curso;
            linha[3] = sano;
            model.addRow(linha);
            alerta.setText("Aluno Cadastrado");
            alerta.setVisible(true);
            codText.setText("");
            codText.requestFocus();
            nomeText.setText("");
            anoText.setText("");
            cursoBox.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cadastrarBotaoActionPerformed

    private void anoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anoTextKeyTyped
        // TODO add your handling code here:
        if(anoText.getText().length() == 2){
            evt.consume();
        }
    }//GEN-LAST:event_anoTextKeyTyped

    private void anoTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anoTextKeyReleased
        // TODO add your handling code here:
        anoText.setText(anoText.getText().replaceAll("[^0-9]",""));
    }//GEN-LAST:event_anoTextKeyReleased

    private void anoTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anoTextKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cursoBox.requestFocus();
        }
    }//GEN-LAST:event_anoTextKeyPressed

    private void anoTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_anoTextFocusLost
        // TODO add your handling code here:
        String sano = anoText.getText();
        if(!sano.isEmpty()){
        if(sano.length()<2){
            sano = "0"+sano;
        }
        anoText.setText(sano);
        }
    }//GEN-LAST:event_anoTextFocusLost

    private void cursoBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cursoBoxKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrarBotao.requestFocus();
        }
    }//GEN-LAST:event_cursoBoxKeyPressed

    private void cursoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursoBoxActionPerformed

    private void nomeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeTextKeyReleased
        // TODO add your handling code here:
        nomeText.setText(nomeText.getText().replaceAll("[^A-Z | ^a-z]",""));
    }//GEN-LAST:event_nomeTextKeyReleased

    private void nomeTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeTextKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            anoText.requestFocus();
        }
    }//GEN-LAST:event_nomeTextKeyPressed

    private void codTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codTextKeyTyped
        // TODO add your handling code here:
        if(codText.getText().length() == 6){
            evt.consume();
        }
    }//GEN-LAST:event_codTextKeyTyped

    private void codTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codTextKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            nomeText.requestFocus();
        }
    }//GEN-LAST:event_codTextKeyPressed

    private void codTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codTextActionPerformed

    private void nomeText2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeText2KeyTyped
        // TODO add your handling code here:
        if(nomeText2.getText().length() == 60){
            evt.consume();
        }
    }//GEN-LAST:event_nomeText2KeyTyped

    private void nomeTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeTextKeyTyped
        // TODO add your handling code here:
        if(nomeText.getText().length() == 60){
            evt.consume();
        }
    }//GEN-LAST:event_nomeTextKeyTyped

    private void codTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codTextFocusLost
        // TODO add your handling code here:
        String codFormatar = codText.getText();
       if(!codFormatar.isEmpty()){
        while(codFormatar.length()<6){
            codFormatar = "0"+codFormatar;
        }
        codText.setText(codFormatar);


        Controlador control = new Controlador();
        String cod = codText.getText();
        Usuario codigo = control.buscarUsuario(cod);
        if(codigo!=null){
            cadastrarBotao.setEnabled(false);
            if(codigo.getTipo().equals("Aluno"))
            alerta.setText("Codigo '" +codFormatar+"' do Aluno '"+codigo.getNome()+"' Já Está Cadastrado");
            else alerta.setText("Codigo " +codFormatar+" do Professor '"+codigo.getNome()+"' Já Está Cadastrado");
            alerta.setVisible(true);
            codText.requestFocus();
            codText.setText("");

        }
        else{
            cadastrarBotao.setEnabled(true);
            alerta.setVisible(false);
        }
       }
    }//GEN-LAST:event_codTextFocusLost

    private void codText2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codText2FocusLost
        // TODO add your handling code here:
        String codFormatar = codText2.getText();
        if(!codFormatar.isEmpty()){
        while(codFormatar.length()<6){
            codFormatar = "0"+codFormatar;
        }
        codText2.setText(codFormatar);

        
        Controlador control = new Controlador();
        String cod = codText2.getText();
        Usuario codigo = control.buscarUsuario(cod);
        if(codigo!=null){
            cadastrarBotao2.setEnabled(false);
            if(codigo.getTipo().equals("Aluno"))
            alerta2.setText("Codigo '" +codFormatar+"' do Aluno '"+codigo.getNome()+"' Já Está Cadastrado");
            else alerta2.setText("Codigo '" +codFormatar+"' do Professor '"+codigo.getNome()+"' Já Está Cadastrado");
            alerta2.setVisible(true);
            codText2.requestFocus();
            codText2.setText("");

        }
        else{
            cadastrarBotao2.setEnabled(true);
            alerta2.setVisible(false);
        }  
        }
    }//GEN-LAST:event_codText2FocusLost

    private void codTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codTextKeyReleased
        // TODO add your handling code here:
        codText.setText(codText.getText().replaceAll("[^0-9]",""));
    }//GEN-LAST:event_codTextKeyReleased

    private void completar(){
       cancelarBotao.setToolTipText("Limpa Todos Os Campos Preenchidos");
       atualizarBotao.setToolTipText("Atualizar Tabela");
       Controlador control = new Controlador();
       ArrayList<Usuario> usuario = control.getUserBusca("Aluno");
       DefaultTableModel model = (DefaultTableModel) tabela.getModel();
       
       String sano;
       
       Aluno al;
       if(usuario!= null){
       for(Usuario user: usuario){
        al=(Aluno) user;
        
        sano = String.valueOf(al.getAno());
        if(sano.length()<2) sano = "0"+sano;
        
        Object linha[] = new Object[4];
        linha[0] = user.getCodUsuario();
        linha[1] = user.getNome();
        linha[2] = al.getCurso();
        linha[3] = sano;
        model.addRow(linha);
        }
        }
    }
    
    private void removerTabela(){
       DefaultTableModel model = (DefaultTableModel) tabela.getModel();
       int tam = tabela.getRowCount();
       for(int i=0; i<tam; i++){
           model.removeRow(0);
       }
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUAddUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUAddUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUAddUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUAddUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IUAddUsuario dialog = new IUAddUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alerta;
    private javax.swing.JLabel alerta2;
    private javax.swing.JTextField anoText;
    private javax.swing.JButton atualizarBotao;
    private javax.swing.JButton atualizarBotao2;
    private javax.swing.JButton cadastrarBotao;
    private javax.swing.JButton cadastrarBotao2;
    private javax.swing.JButton cancelarBotao;
    private javax.swing.JButton cancelarBotao2;
    private javax.swing.JTextField codText;
    private javax.swing.JTextField codText2;
    private javax.swing.JComboBox<String> cursoBox;
    private javax.swing.JComboBox<String> cursoBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1P;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2P;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3P;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane2P;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nomeText;
    private javax.swing.JTextField nomeText2;
    private javax.swing.JTextField pesquisa;
    private javax.swing.JTextField pesquisa2;
    private javax.swing.JButton removerBotao;
    private javax.swing.JButton removerBotao2;
    private javax.swing.JButton sairBotao;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabela2;
    // End of variables declaration//GEN-END:variables
}
